meta_name: "SHAN MUA"
meta_title: "SHAN MUA - Make Up Artistry"
meta_description: "Portfolio of MUA Shannon Herdman"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
